Lambda-School-Labs/CS8-backwoods

client/package-lock.json
client/src/App.jsx
client/src/components/Landing/BuyNow.jsx
client/src/components/Landing/Modal.jsx
client/src/components/Landing/PageContent.jsx
client/src/components/Landing/SignInForm.jsx
client/src/components/Landing/SignUpForm.jsx
client/src/components/Landing/Tabs.jsx
client/src/index.css
client/src/index.js
package-lock.json

Set up the landing page for the root of the front end of the application.

Landing Page Interface

---

client/src/components/Landing/Carousel.jsx
client/src/components/Landing/PageContent.jsx

Image stepper added to the landing page with 3 images. For the sake of ease, the images are hosted on imgur, this should be changed to a more stable CDN or a database before launching into production.

Carousel added to landing page

---

config.js
controllers/login.js
middleware/authMiddleware.js
models/user.js
package.json
routes/routes.js
yarn.lock

`/signup` route saves new user and hashes password with bcrypt.
`/login` route checks if user exists. If so, bcrypt checks save has to saved password and gives back a JWT token.,
- [xI have performed a self-review of my own code

Backend jwt/routes

---

controllers/login.js
models/user.js

Added `/signup` route that creates new user in the DB and hashes password with bcrypt
Added `/login` route that checks hashed password and returns a JWT token.

Backend jwt/routes2

---

client/src/components/Account/AccountForm.jsx
client/src/components/Billing/BillingForm.jsx
client/src/components/Debug/DebugRoutes.jsx
client/src/components/Nav/Nav.jsx
client/src/components/Trip/Trip.jsx
client/src/components/Trip/TripCreate.jsx
client/src/components/TripList/TripList.jsx
client/src/components/TripList/TripListEmpty.jsx
client/src/index.css
client/src/index.js
package-lock.json

It's not possible to click through the entire front end. Developer doesn't need to worry about authenticating every time, and doesn't need to worry about finding the page they need to work on thanks to the dev tool at the bottom right of the page. They can select any page they'd like and immediately see the effects. It should save time, effort, and increase efficiency of working on the front end.
Additionally: https://github.com/frogr/cs8backwoods-frontend-notes for notes about what content goes where in case anything is not obvious

Frontend skeleton with debug tool

---

README.md
client/package.json
client/src/components/Landing/SignInForm.jsx
client/src/components/Landing/SignUpForm.jsx
client/yarn.lock
controllers/createUser.js

Connected the front-end to back-end with signup and login. can now create a user through the front-end and sign in with the created user in the front-end and receive a JWT token. 

Front end sign up

---

procfile

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

added procfile

---

server.js

Added port variable to server.js to get deploy working on Heroku  

added port to get deploy working

---

config.json
models/index.js
package.json

Changed models/index.js to connect to the deployed server when clicking the Heroku link or to connect to the local database when running with yarn start through a terminal

Deploy now working

---

client/src/App.jsx
controllers/changePassword.js
models/user.js
routes/routes.js

* deploy axios calls
* add route for change password

add route for change password

---

client/src/components/Trip/Coordinates.jsx
client/src/components/Trip/Map.jsx
client/src/components/Trip/Trip.jsx
client/src/components/Trip/TripInfo.jsx
client/src/index.css

Added a trip 1 example with google maps, a drawn polygon, as well as an expansion menu on the right that displays the coordinates. Very primitive example of what a trip should roughly look like 

Hardcoded trip 1 with Google maps example

---

README.md
client/src/App.jsx
client/src/components/TripCreate/TripCreate.jsx
client/src/components/TripCreate/TripCreateForm.jsx
client/src/components/TripList/MainTripList.jsx
client/src/components/User/User.jsx

Creating a user and getting the user back when going to '/:user' works, Also took out all of the
commented out code that we don't need and added commented out routes to the deployed server.  

Create trip routing front end

---

README.md
client/src/components/TripCreate/TripCreateForm.jsx

[x] corrected url in deploy version of an axios call in `TripCreateForm.jsx`
[x] add change password route to docs
[x] add deploy URL to docs

Update readme bug fix

---

controllers/markers.js
models/index.js
models/markers.js
models/trips.js
models/user.js
routes/routes.js

[x] Made new createMarker route
[x] fixed relationships in database
[x] Made show marker route
[x] cleaned up models

Test models

---

client/package.json
client/src/components/TripCreate/ExpansionPanelForm.jsx
client/src/components/TripCreate/Map.jsx
client/src/components/TripCreate/TripCreate.jsx
client/src/components/TripCreate/TripCreateForm.jsx
client/src/components/TripCreate/Waypoint.jsx
client/src/components/TripCreate/WaypointList.jsx
client/src/components/TripList/MainTripList.jsx
client/src/components/TripList/Trip.jsx
client/src/components/User/User.jsx
controllers/markers.js
controllers/trips.js
models/trips.js

[x] Added createBulk to markers in the back-end
[x] Create trip and create markers are connected in the front-end (have multiple markers per trip)
[x] Cleaned up console logs
[x] Add marker works
[x] Added slug to trip for URL
[x] Lifted up state from create-trip-forum and brought it to create trip.
[x] Open trip view is set up  when  clicking on a trip

Backend to frontend

---

client/package-lock.json
client/src/App.jsx
client/src/components/Debug/DebugRoutes.jsx
client/src/components/Nav/NavBreadcrumb.jsx
client/src/components/TripCreate/Coordinates.jsx
client/src/components/TripCreate/Map.jsx
client/src/components/TripCreate/TripCreate.jsx
client/src/components/TripCreate/TripCreateForm.jsx
client/src/components/TripList/MainTripList.jsx
client/src/components/TripList/Trip.jsx
client/src/components/TripList/TripList.jsx
client/src/components/TripList/TripListEmpty.jsx
client/src/components/User/User.jsx
client/src/index.css

Reverts Lambda-School-Labs/CS8-backwoods#34

Revert "Interface bugfixes "

---

client/src/components/Account/Account.css
client/src/components/Account/AccountForm.jsx

Basic styling for account page.

Account styles

---

client/src/components/TripOpen/SingleTripOpen.jsx
client/src/components/TripOpen/TripOpen.jsx
client/src/components/TripOpen/TripOpenName.jsx
client/src/components/TripOpen/TripOpenWaypointList.jsx
client/src/components/TripOpen/tripOpenStyling.css
client/src/index2.css
controllers/trips.js
models/trips.js
routes/routes.js

[x] Trip Open View now  has the  markers associated with the trip
[x]  Started Archive trip in the back-end(made archive trip route and put Archived onto model)
[x] Filtered for non-archived trips in the getTrips route

Trip Open View/Started Archive Trips

---

client/src/components/Account/Account.css
client/src/components/Billing/Billing.css
client/src/components/Billing/CheckoutForm.jsx

Adjusted the styling of the Account and Billing views to look less sporadic and more cohesive in the application. Much easier to type into the stripe component now. 

Account + Billing views 

---

client/src/components/Archived/Archived.jsx
client/src/components/Archived/GetArchived.jsx
client/src/components/Archived/SingleAchived.jsx
client/src/components/User/User.jsx

Archived trips now display on the front-end and update the back-end
Used postman to test routes and used chrome dev tools for the view.

Archive front end

---

client/src/components/Archived/Archived.jsx
client/src/components/Archived/GetArchived.jsx
client/src/components/Archived/SingleAchived.jsx
client/src/components/Billing/CheckoutForm.jsx
client/src/components/TripList/MainTripList.jsx
client/src/components/User/User.jsx

[x] Added snack bar success/error messages when Archiving a trip/Unarchiving a trip.
[x] Added snack bar success/error messages when completing a Purchase
.

Snackbars in Archive/billing working

---

client/src/components/Archived/GetArchived.jsx
client/src/components/TripCreate/TripCreate.jsx
client/src/components/TripOpen/TripOpen.jsx
client/src/components/User/User.jsx

[x] Added commented out routes for the deployed version

Adding comments for deployed routes

---

client/src/components/Nav/NavBreadcrumb.jsx
client/src/components/TripOpen/Map.jsx
client/src/components/TripOpen/SingleTripOpen.jsx
client/src/components/TripOpen/TripOpen.jsx
client/src/components/TripOpen/TripOpenWaypointList.jsx

On the specific trip page, the map now shows saved markers on it. Also fixed some console errors regarding mapping without `key` props.

Open trip page now shows markers

---

client/src/components/TripList/MainTripList.jsx
client/src/components/TripList/SingleTrip.jsx
client/src/index.css

Set default font to Roboto and animated the trip list
Tested in Chrome

Default font Roboto and Animated the trip list

---

client/package-lock.json
client/src/components/Archived/GetArchived.jsx
client/src/components/Nav/Nav.css
client/src/components/Nav/Nav.jsx
client/src/components/Nav/NavBar.jsx
client/src/components/TripCreate/TripCreate.jsx
client/src/components/TripList/MainTripList.jsx
client/src/components/User/User.jsx
client/src/index.js

If user tries to leave trip create before saving, a modal will pop up asking to confirm their decision.
Tested in Chrome dev tools and reach dev tools

Modal unsaved trips

---

client/src/components/Account/AccountForm.jsx
client/src/components/Archived/Archived.css
client/src/components/Archived/Archived.jsx
client/src/components/Archived/SingleAchived.jsx
client/src/components/Billing/BillingForm.jsx
client/src/components/Nav/Nav.css
client/src/components/Nav/NavBar.jsx
client/src/components/Nav/NavBreadcrumb.jsx
client/src/components/SignInOut/SignInOut.jsx
client/src/components/TripCreate/TripCreate.jsx
client/src/components/TripList/MainTripList.jsx
client/src/components/User/User.jsx

[x] Added Transitions to most of the interface
[x] Routing works properly now with the userHasNoTrips page delete
[x] Nav bar CSS tweaks

Transitions

---

client/src/components/Account/Account.css
client/src/components/Account/AccountForm.jsx
client/src/components/Archived/Archived.css
client/src/components/SignInOut/SignInForm.jsx
client/src/components/SignInOut/SignInOut.css
client/src/components/SignInOut/SignInOut.jsx
client/src/components/SignInOut/SignUpForm.jsx
client/src/components/SignInOut/Tabs.jsx
client/src/components/TripCreate/TripSaveModal.jsx
client/src/components/TripList/TripList.css
client/src/components/TripOpen/Map.jsx

Changed padding around trips and archived
Changed title font weight inside trip view and archived view
Changed all buttons from black text on green to white text on green 
Fixed typo
Changed the default coordinates for one of the map views, I think Aaron changed it too in his PR so it's double changed but that's okay it won't conflict
Fixes Bri's suggestions for style changes

Bri's requested style changes

---

client/public/index.html
client/src/components/Landing/Landing.jsx
client/src/components/SignInOut/SignInOut.css
client/src/components/SignInOut/SignInOut.jsx
client/src/components/TripCreate/MakerSaveModal.jsx
client/src/components/TripCreate/TripCreate.css
client/src/components/TripCreate/TripCreate.jsx
client/src/components/TripCreate/TripCreateForm.jsx
client/src/components/TripCreate/Waypoint.jsx
client/src/components/TripCreate/WaypointCreateCard.jsx
client/src/components/TripCreate/WaypointList.jsx
client/src/components/TripOpen/TripOpenWaypointList.jsx
client/src/components/User/User.jsx

Trip creact/bug fixes

---

client/src/components/TripCreate/MakerSaveModal.jsx
client/src/components/TripCreate/TripCreate.jsx
client/src/components/TripCreate/Waypoint.jsx
client/src/components/TripCreate/WaypointCreateCard.jsx
client/src/components/TripCreate/WaypointList.jsx
client/src/components/TripOpen/SingleTripOpen.jsx
client/src/components/TripOpen/TripOpenWaypointList.jsx

Now correct modal is displays for trip create without marks and marks without names

fixed correct modal displaying and format of dates
